# Generated by Django 4.1.13 on 2024-03-22 21:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('puede_procesar_contingencia', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='C001AmbienteDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='CODIGO', max_length=2)),
                ('valor', models.CharField(blank=True, db_column='VALOR', max_length=20, null=True)),
            ],
            options={
                'db_table': 'C001_AMBIENTE_DESTINO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C002TipoDocumento',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=3, primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, db_column='VALOR', max_length=50, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('version_work', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'C002_TIPO_DOCUMENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C003ModeloFacturacion',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=35)),
            ],
            options={
                'db_table': 'C003_MODELO_FACTURACION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C004TipoTransmision',
            fields=[
                ('codigo', models.IntegerField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=35)),
            ],
            options={
                'db_table': 'C004_TIPO_TRANSMISION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C005TipoContingencia',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=50)),
            ],
            options={
                'db_table': 'C005_TIPO_CONTINGENCIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C006RetencionIva',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=50)),
            ],
            options={
                'db_table': 'C006_RETENCION_IVA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C007TipoGeneraciondoc',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=50)),
            ],
            options={
                'db_table': 'C007_TIPO_GENERACIONDOC',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C009TipoEstablecimiento',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'C009_TIPO_ESTABLECIMIENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C010CodtipoServicio',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=50)),
            ],
            options={
                'db_table': 'C010_CODTIPO_SERVICIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C011TipoItem',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='VALOR', max_length=50)),
            ],
            options={
                'db_table': 'C011_TIPO_ITEM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C012Departamento',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=125, null=True)),
            ],
            options={
                'db_table': 'C012_DEPARTAMENTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C013Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=2)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=125)),
                ('cod_departamento', models.ForeignKey(blank=True, db_column='COD_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipio_departamento', to='dtesv.c012departamento')),
            ],
            options={
                'db_table': 'C013_MUNICIPIO',
                'managed': True,
                'unique_together': {('codigo', 'cod_departamento')},
            },
        ),
        migrations.CreateModel(
            name='C015Tributos',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'C015_TRIBUTOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C016CondicionOperacion',
            fields=[
                ('codigo', models.IntegerField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=25, null=True)),
            ],
            options={
                'db_table': 'C016_CONDICION_OPERACION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C019ActividadEconomica',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=250)),
            ],
            options={
                'db_table': 'C019_ACTIVIDAD_ECONOMICA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C020Pais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=125, null=True)),
            ],
            options={
                'db_table': 'C020_PAIS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C022TipoDocumentoIdentificacionReceptor',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=25)),
            ],
            options={
                'db_table': 'C022_TIPO_DOCUMENTO_IDENTIFICACION_RECEPTOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C025BienesRemitidosTitulos',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'C025_BIENES_REMITIDOS_TITULOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C027RecintoFiscal',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'db_table': 'C027_Recinto_fiscal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C028Regimen',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'C028_Regimen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C029TipoPersona',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'C029_Tipo_persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='C031Incoterms',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'C031_INCOTERMS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CAT023TipodeDocumentoenContingencia',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=3, primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, db_column='VALOR', max_length=50, null=True)),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('version_work', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'C002_TIPO_DOCUMENTO_CONTINGENCIA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/opt/DTESV/dtesv/Facturacion_electronica/dtesv/company_logos/'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('clase_documento', models.CharField(db_column='clase_documento', max_length=2)),
                ('num_documento', models.CharField(db_column='Num_documento', max_length=50)),
                ('fecEmi', models.DateField(blank=True, db_column='fecEmi', null=True)),
                ('totalNoSuj', models.DecimalField(blank=True, db_column='totalNoSuj', decimal_places=6, max_digits=18, null=True)),
                ('totalExenta', models.DecimalField(blank=True, db_column='totalExenta', decimal_places=6, max_digits=18, null=True)),
                ('horEmi', models.TimeField(blank=True, db_column='horEmi', null=True)),
                ('descuGravada', models.DecimalField(blank=True, db_column='descuGravada', decimal_places=6, max_digits=18, null=True)),
                ('porcentajeDescuento', models.DecimalField(blank=True, db_column='porcentajeDescuento', decimal_places=6, max_digits=18, null=True)),
                ('totalDescu', models.DecimalField(blank=True, db_column='totalDescu', decimal_places=6, max_digits=18, null=True)),
                ('iva', models.DecimalField(blank=True, db_column='iva', decimal_places=6, max_digits=18, null=True)),
                ('ivaRete1', models.DecimalField(blank=True, db_column='ivaRete1', decimal_places=6, max_digits=18, null=True)),
                ('ivaPerci1', models.DecimalField(blank=True, db_column='ivaPerci1', decimal_places=6, max_digits=18, null=True)),
                ('reteRenta', models.DecimalField(blank=True, db_column='reteRenta', decimal_places=6, max_digits=18, null=True)),
                ('totalGravada', models.DecimalField(blank=True, db_column='totalGravada', decimal_places=6, max_digits=18, null=True)),
                ('subTotalVentas', models.DecimalField(blank=True, db_column='subTotalVentas', decimal_places=6, max_digits=18, null=True)),
                ('descuNoSuj', models.DecimalField(blank=True, db_column='descuNoSuj', decimal_places=6, max_digits=18, null=True)),
                ('descuExenta', models.DecimalField(blank=True, db_column='descuExenta', decimal_places=6, max_digits=18, null=True)),
                ('totalNoGravado', models.DecimalField(blank=True, db_column='totalNoGravado', decimal_places=6, max_digits=18, null=True)),
                ('saldoFavor', models.DecimalField(blank=True, db_column='saldoFavor', decimal_places=6, max_digits=18, null=True)),
                ('totalPagar', models.DecimalField(blank=True, db_column='totalPagar', decimal_places=6, max_digits=18, null=True)),
                ('montoTotalOperacion', models.DecimalField(blank=True, db_column='montoTotalOperacion', decimal_places=6, max_digits=18, null=True)),
                ('totalLetras', models.CharField(db_column='totalLetras', max_length=255)),
                ('pagos', models.IntegerField(blank=True, db_column='pagos', null=True)),
                ('numPagoElectronico', models.CharField(blank=True, db_column='numPagoElectronico', max_length=50, null=True)),
                ('vendedor_id', models.CharField(blank=True, db_column='vendedor_id', max_length=10, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=10, null=True)),
                ('numeroControl', models.CharField(blank=True, db_column='numeroControl', max_length=255, null=True)),
                ('codigoGeneracion', models.CharField(db_column='codigoGeneracion', max_length=36, primary_key=True, serialize=False)),
                ('motivoContin', models.CharField(blank=True, db_column='motivoContin', max_length=255, null=True)),
                ('tipoMoneda', models.CharField(blank=True, db_column='tipoMoneda', max_length=10, null=True)),
                ('cod_entrega', models.CharField(blank=True, db_column='cod_entrega', max_length=10, null=True)),
                ('observaciones_entrega', models.CharField(blank=True, db_column='observaciones_entrega', max_length=255, null=True)),
                ('numeroDocumento_rel_guid', models.CharField(blank=True, db_column='numeroDocumento_rel_guid', max_length=36, null=True)),
                ('numeroDocumento_rel_corr', models.CharField(blank=True, db_column='numeroDocumento_rel_corr', max_length=55, null=True)),
                ('tipoItemExpor', models.IntegerField(blank=True, db_column='tipoItemExpor', null=True)),
                ('seguro', models.DecimalField(blank=True, db_column='seguro', decimal_places=6, max_digits=18, null=True)),
                ('flete', models.DecimalField(blank=True, db_column='flete', decimal_places=6, max_digits=18, null=True)),
                ('selloRecibido', models.CharField(blank=True, db_column='selloRecibido', max_length=50, null=True)),
                ('observaciones_mh', models.TextField(blank=True, db_column='observaciones_mh', null=True)),
                ('fecha_proceso_mh', models.DateTimeField(blank=True, db_column='fecha_proceso_mh', null=True)),
                ('cod_sucursal', models.CharField(blank=True, db_column='cod_sucursal', max_length=8, null=True)),
                ('observacion_proceso', models.TextField(blank=True, db_column='observacion_proceso', null=True)),
                ('estado_anulado', models.TextField(blank=True, db_column='estado_anulado', null=True)),
                ('selloInvalidacion', models.CharField(blank=True, db_column='selloInvalidacion', max_length=50, null=True)),
                ('fecha_anula_mh', models.DateTimeField(blank=True, db_column='fecha_anula_mh', null=True)),
                ('en_contingencia', models.BooleanField(db_column='en_contingencia', default=False)),
                ('enviado_movil', models.BooleanField(db_column='enviado_movil', default=False)),
                ('codigoLotelocal', models.CharField(blank=True, db_column='codigoGeneracionLote', max_length=36, null=True)),
                ('codigoLotemh', models.CharField(blank=True, db_column='codigo_lote_mh', max_length=36, null=True)),
                ('email_enviado', models.BooleanField(db_column='email_enviado', default=False)),
                ('totalSujetoRetenido', models.DecimalField(blank=True, db_column='totalSujetoRetenido', decimal_places=6, max_digits=18, null=True)),
                ('totalIVAretenido', models.DecimalField(blank=True, db_column='totalIVAretenido', decimal_places=6, max_digits=18, null=True)),
                ('rutaEntrega', models.CharField(blank=True, db_column='rutaEntrega', max_length=6, null=True)),
                ('orden_compra', models.CharField(blank=True, db_column='orden_compra', max_length=120, null=True)),
                ('motivoInvalidacion', models.CharField(blank=True, db_column='motivoInvalidacion', max_length=255, null=True)),
                ('codigoGenInvalida', models.CharField(blank=True, db_column='codigoGenInvalida', max_length=36, null=True)),
                ('anuladoErp', models.BooleanField(db_column='anuladoErp', default=False)),
                ('bienTitulo', models.ForeignKey(blank=True, db_column='bienTitulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_bienTitulo', to='dtesv.c025bienesremitidostitulos')),
                ('codIncoterms', models.ForeignKey(blank=True, db_column='codIncoterms', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_codIncoterms', to='dtesv.c031incoterms')),
                ('codigo_iva', models.ForeignKey(blank=True, db_column='codigo_iva', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_codigo_iva', to='dtesv.c015tributos')),
                ('condicionOperacion', models.ForeignKey(blank=True, db_column='condicionOperacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_condicionOperacion', to='dtesv.c016condicionoperacion')),
            ],
            options={
                'db_table': 'DOCUMENTOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=14)),
                ('dui', models.CharField(max_length=14)),
                ('nrc', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=250)),
                ('nombrecomercial', models.CharField(blank=True, db_column='nombreComercial', max_length=150, null=True)),
                ('direccion_complemento', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('codestablemh', models.CharField(blank=True, db_column='codEstableMH', max_length=4, null=True)),
                ('codestable', models.CharField(blank=True, db_column='codEstable', max_length=4, null=True)),
                ('codpuntoventamh', models.CharField(blank=True, db_column='codPuntoVentaMH', max_length=4, null=True)),
                ('codpuntoventa', models.CharField(blank=True, db_column='codPuntoVenta', max_length=4, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=125, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('passwordpri', models.TextField(blank=True, db_column='passwordPri', null=True)),
                ('mh_auth', models.CharField(blank=True, max_length=175, null=True)),
                ('ambiente_trabajo', models.ForeignKey(blank=True, db_column='ambiente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ambiente_trabajo', to='dtesv.c001ambientedestino')),
                ('codactividad', models.ForeignKey(db_column='codActividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_codActividad', to='dtesv.c019actividadeconomica')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_departamento', to='dtesv.c012departamento')),
                ('municipio', models.ForeignKey(blank=True, db_column='municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_municipio', to='dtesv.c013municipio')),
                ('recintoFiscal', models.ForeignKey(blank=True, db_column='recintoFiscal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_recintoFiscal', to='dtesv.c027recintofiscal')),
                ('regimen', models.ForeignKey(blank=True, db_column='regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_regimen', to='dtesv.c028regimen')),
                ('tipoItemExpor', models.ForeignKey(blank=True, db_column='tipoItemExpor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_tipoItemExpor', to='dtesv.c011tipoitem')),
                ('tipoestablecimiento', models.ForeignKey(db_column='tipoEstablecimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='dtesv.c009tipoestablecimiento')),
            ],
            options={
                'db_table': 'EMISOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtrosDocumentosAsociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doc', models.CharField(max_length=50)),
                ('guid_doc_asoc', models.CharField(blank=True, max_length=36, null=True)),
                ('num_doc_asoc', models.CharField(max_length=50)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('other_tipo_documento_asoc', models.CharField(max_length=3)),
                ('coddocasociado', models.IntegerField(blank=True, db_column='codDocAsociado', null=True)),
                ('tipo_documento_oasoc', models.CharField(max_length=3)),
                ('emisor_id', models.IntegerField()),
            ],
            options={
                'db_table': 'OTROS_DOCUMENTOS_ASOCIADOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('codigo', models.CharField(db_column='codigo', max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=249, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=False)),
                ('tipo', models.CharField(blank=True, max_length=16, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=16, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('codigo', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('numdocumento', models.CharField(db_column='numDocumento', max_length=18)),
                ('nrc', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nombrecomercial', models.CharField(db_column='nombreComercial', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('tiporeceptor', models.CharField(blank=True, db_column='tipoReceptor', max_length=10, null=True)),
                ('codactividad', models.ForeignKey(db_column='codActividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_codActividad', to='dtesv.c019actividadeconomica')),
                ('codigoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtesv.receptor')),
                ('codpais', models.ForeignKey(blank=True, db_column='codPais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_codpais', to='dtesv.c020pais')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_departamento', to='dtesv.c012departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_empresa', to='dtesv.emisor')),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_municipio', to='dtesv.c013municipio')),
                ('tipodocumento', models.ForeignKey(blank=True, db_column='tipodocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_tipo_documento_identific', to='dtesv.c022tipodocumentoidentificacionreceptor')),
                ('tipopersona', models.ForeignKey(blank=True, db_column='tipoPersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptor_tipopersona', to='dtesv.c029tipopersona')),
            ],
            options={
                'db_table': 'RECEPTOR',
                'managed': True,
                'unique_together': {('codigo', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('numdocumento', models.CharField(db_column='numDocumento', max_length=18)),
                ('nrc', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nombrecomercial', models.CharField(db_column='nombreComercial', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('tiporeceptor', models.CharField(blank=True, db_column='tipoReceptor', max_length=10, null=True)),
                ('codactividad', models.ForeignKey(db_column='codActividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_codActividad', to='dtesv.c019actividadeconomica')),
                ('codigoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtesv.proveedor')),
                ('codpais', models.ForeignKey(blank=True, db_column='codPais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_codpais', to='dtesv.c020pais')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_departamento', to='dtesv.c012departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_empresa', to='dtesv.emisor')),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_municipio', to='dtesv.c013municipio')),
                ('tipodocumento', models.ForeignKey(blank=True, db_column='tipodocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_tipo_documento_identific', to='dtesv.c022tipodocumentoidentificacionreceptor')),
                ('tipopersona', models.ForeignKey(blank=True, db_column='tipoPersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_tipopersona', to='dtesv.c029tipopersona')),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': True,
                'unique_together': {('codigo', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Parametros', max_length=255)),
                ('url_firmador', models.CharField(max_length=255)),
                ('url_autentication', models.CharField(max_length=255)),
                ('url_dte', models.CharField(max_length=255)),
                ('url_dte_lote', models.CharField(default='https://apitest.dtes.mh.gob.sv/fesv/recepcionlote/', max_length=255)),
                ('url_dte_consulta', models.CharField(default='https://api.dtes.mh.gob.sv/fesv/recepcion/consultadte/', max_length=255)),
                ('url_dte_lote_consulta', models.CharField(default='https://apitest.dtes.mh.gob.sv/fesv/recepcion/consultadtelote/', max_length=255)),
                ('url_invalidacion', models.CharField(default='https://apitest.dtes.mh.gob.sv/fesv/anulardte', max_length=255)),
                ('url_contingencia', models.CharField(default='https://apitest.dtes.mh.gob.sv/fesv/contingencia', max_length=255)),
                ('url_email_api_login', models.CharField(default='http://192.168.1.48:4000/api/login', max_length=255)),
                ('user_login_email', models.CharField(default='mi user', max_length=50)),
                ('pass_login_email', models.CharField(default='mi pass', max_length=255)),
                ('url_email_api', models.CharField(default='http://192.168.1.48:4000/api/correo', max_length=255)),
                ('url_getconsectivoSF', models.CharField(default='http://192.168.1.53:5010/api/consecutivos/', max_length=255)),
                ('url_setconsectivoSF', models.CharField(default='http://192.168.1.53:5010/api/consecutivosUp/', max_length=255)),
                ('interval_ejecute', models.IntegerField()),
                ('autmoatizacion_activa', models.BooleanField(default=True)),
                ('hora_inicio', models.IntegerField(default=9)),
                ('hora_fin', models.IntegerField(default=18)),
                ('intervalo_tiempo', models.IntegerField(default=60000)),
                ('attachment_email_path', models.CharField(default='C:\\app\\', max_length=255)),
                ('attachment_files_path', models.CharField(default='C:\\app\\', max_length=255)),
                ('ambiente', models.ForeignKey(blank=True, db_column='ambienteTrabajo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_ambiente_trabajo', to='dtesv.c001ambientedestino')),
                ('company_id', models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parametros_company_id', to='dtesv.company')),
                ('contigencia_defaul', models.ForeignKey(blank=True, db_column='contigencia_defaul', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_contingencia', to='dtesv.c005tipocontingencia')),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosLote',
            fields=[
                ('version', models.IntegerField(blank=True, db_column='version', null=True)),
                ('versionApp', models.IntegerField(blank=True, db_column='versionApp', null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=50, null=True)),
                ('idEnvio', models.CharField(db_column='idEnvio', max_length=36, primary_key=True, serialize=False)),
                ('codigoLote', models.CharField(blank=True, db_column='codigoLote', max_length=36, null=True)),
                ('fhProcesamiento', models.DateTimeField(blank=True, db_column='fhProcesamiento', null=True)),
                ('clasificaMsg', models.IntegerField(blank=True, db_column='clasificaMsg', null=True)),
                ('codigoMsg', models.CharField(blank=True, db_column='codigoMsg', max_length=10, null=True)),
                ('descripcionMsg', models.TextField(blank=True, db_column='descripcionMsg', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('ambiente', models.ForeignKey(blank=True, db_column='ambienteTrabajo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentosLote_ambiente_trabajo', to='dtesv.c001ambientedestino')),
                ('detalledocumentoslote', models.ManyToManyField(blank=True, related_name='detalledocumentoslote', to='dtesv.documentos')),
            ],
            options={
                'db_table': 'DOCUMENTOS_LOTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numItem', models.IntegerField(db_column='numItem')),
                ('tipoItem', models.CharField(blank=True, db_column='tipoItem', max_length=2, null=True)),
                ('cantidad', models.DecimalField(blank=True, db_column='cantidad', decimal_places=6, max_digits=18, null=True)),
                ('codigo', models.CharField(blank=True, db_column='codigo', max_length=15, null=True)),
                ('uniMedida', models.IntegerField(db_column='uniMedida')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=188)),
                ('precioUni', models.DecimalField(db_column='precioUni', decimal_places=6, max_digits=18)),
                ('montoDescu', models.DecimalField(db_column='montoDescu', decimal_places=6, max_digits=18)),
                ('ventaNoSuj', models.DecimalField(db_column='ventaNoSuj', decimal_places=6, max_digits=18)),
                ('ventaExenta', models.DecimalField(db_column='ventaExenta', decimal_places=6, max_digits=18)),
                ('ventaGravada', models.DecimalField(db_column='ventaGravada', decimal_places=6, max_digits=18)),
                ('noGravado', models.DecimalField(db_column='noGravado', decimal_places=6, max_digits=18)),
                ('ivaItem', models.DecimalField(db_column='ivaItem', decimal_places=6, max_digits=18)),
                ('psv', models.DecimalField(db_column='psv', decimal_places=6, default=0.0, max_digits=18)),
                ('numeroDocumento', models.CharField(blank=True, db_column='numeroDocumento', max_length=36, null=True)),
                ('fechaEmision', models.DateField(blank=True, db_column='fechaEmision', null=True)),
                ('codTributo', models.ForeignKey(blank=True, db_column='codTributo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_codTributo', to='dtesv.c015tributos')),
                ('codigoGeneracion_id', models.ForeignKey(blank=True, db_column='codigoGeneracion_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_codigoGeneracion_id', to='dtesv.documentos')),
                ('codigoRetencionMH', models.ForeignKey(blank=True, db_column='codigoRetencionMH', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_codigoRetencionMH', to='dtesv.c006retencioniva')),
                ('tipoDoc', models.ForeignKey(blank=True, db_column='tipoDoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_tipoDoc', to='dtesv.c007tipogeneraciondoc')),
                ('tipoDte', models.ForeignKey(blank=True, db_column='tipoDte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_tipoDte', to='dtesv.c002tipodocumento')),
            ],
            options={
                'db_table': 'DOCUMENTOS_DETALLE',
                'managed': True,
                'unique_together': {('numItem', 'codigo', 'codigoGeneracion_id')},
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_detalles', to='dtesv.documentosdetalle'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='emisor_id',
            field=models.ForeignKey(blank=True, db_column='emisor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_emisor_id', to='dtesv.emisor'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='proveedor_id',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_proveedor_id', to='dtesv.proveedor'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='receptor_id',
            field=models.ForeignKey(blank=True, db_column='receptor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_receptor_id', to='dtesv.receptor'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='receptor_origen',
            field=models.ForeignKey(blank=True, db_column='receptor_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_receptor_origen_id', to='dtesv.receptor'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='recintoFiscal',
            field=models.ForeignKey(blank=True, db_column='recintoFiscal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_recintoFiscal', to='dtesv.c027recintofiscal'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='regimen',
            field=models.ForeignKey(blank=True, db_column='regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_regimen', to='dtesv.c028regimen'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipoContingencia',
            field=models.ForeignKey(blank=True, db_column='tipoContingencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipoContingencia', to='dtesv.c005tipocontingencia'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipoModelo',
            field=models.ForeignKey(blank=True, db_column='tipoModelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipoModelo', to='dtesv.c003modelofacturacion'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipoOperacion',
            field=models.ForeignKey(blank=True, db_column='tipoOperacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipoOperacion', to='dtesv.c007tipogeneraciondoc'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipoTransmision',
            field=models.ForeignKey(blank=True, db_column='tipoTransmision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipoTransmision', to='dtesv.c004tipotransmision'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipodocumento',
            field=models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipo_documento', to='dtesv.c002tipodocumento'),
        ),
        migrations.CreateModel(
            name='contingencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('codigoGeneracion', models.CharField(max_length=36, unique=True)),
                ('fTransmision', models.DateField()),
                ('hTransmision', models.TimeField()),
                ('fInicio', models.DateField()),
                ('fFin', models.DateField()),
                ('hInicio', models.TimeField()),
                ('hFin', models.TimeField()),
                ('motivoContingencia', models.CharField(max_length=500, null=True)),
                ('selloRecepcion', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=10, null=True)),
                ('observacion_proceso', models.TextField(blank=True, db_column='observaciones_proceso', null=True)),
                ('observaciones_mh', models.TextField(blank=True, db_column='observaciones_mh', null=True)),
                ('ambiente', models.ForeignKey(blank=True, db_column='ambiente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contingencia_ambiente', to='dtesv.c001ambientedestino')),
                ('detalleDTE', models.ManyToManyField(blank=True, related_name='Documentos_contingencia', to='dtesv.documentos')),
                ('emisor', models.ForeignKey(blank=True, db_column='emisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contingencia_emisor_id', to='dtesv.emisor')),
                ('tipoContingencia', models.ForeignKey(blank=True, db_column='tipoContingencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contingencia_tipo', to='dtesv.c005tipocontingencia')),
            ],
            options={
                'db_table': 'CONTINGENCIA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='emisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtesv.emisor'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('numRec', models.CharField(db_column='numRec', max_length=12, primary_key=True, serialize=False)),
                ('codigo_forma_pago', models.CharField(blank=True, db_column='codigo_forma_pago', max_length=20, null=True)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=6, max_digits=18)),
                ('plazo', models.CharField(db_column='plazo', max_length=12)),
                ('periodo', models.CharField(db_column='periodo', max_length=12)),
                ('codigogeneracion_doc', models.ForeignKey(blank=True, db_column='codigoGeneracion_doc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos_codigoGeneracion_doc', to='dtesv.documentos')),
            ],
            options={
                'db_table': 'PAGOS',
                'managed': True,
                'unique_together': {('numRec', 'codigogeneracion_doc')},
            },
        ),
        migrations.CreateModel(
            name='ExtencionEntrega',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=125, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10, null=True)),
                ('docuentrega', models.CharField(blank=True, db_column='docuEntrega', max_length=20, null=True)),
                ('id_emisor', models.ForeignKey(db_column='id_emisor', on_delete=django.db.models.deletion.DO_NOTHING, to='dtesv.emisor')),
            ],
            options={
                'db_table': 'EXTENCION_ENTREGA',
                'managed': True,
                'unique_together': {('codigo', 'id_emisor')},
            },
        ),
        migrations.CreateModel(
            name='DocumentosAsociados',
            fields=[
                ('codigoGeneracion', models.CharField(db_column='codigoGeneracion', max_length=36, primary_key=True, serialize=False)),
                ('codigoGeneracion_asoc', models.ForeignKey(db_column='codigoGeneracion_asoc', on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_asociado_codigoGeneracion_asoc', to='dtesv.documentos')),
                ('id_emisor', models.ForeignKey(db_column='id_emisor', on_delete=django.db.models.deletion.DO_NOTHING, to='dtesv.emisor')),
            ],
            options={
                'db_table': 'DOCUMENTOS_ASOCIADOS',
                'managed': True,
                'unique_together': {('codigoGeneracion', 'codigoGeneracion_asoc')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentos',
            unique_together={('codigoGeneracion', 'tipodocumento', 'emisor_id')},
        ),
    ]
