# Generated by Django 4.1.13 on 2024-03-27 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dtesv.company')),
                ('users', models.ManyToManyField(blank=True, related_name='sucursal_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
