# Generated by Django 4.1.9 on 2023-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='C:\\Users\\turciosi\\Documents\\Github\\DjangoApp\\Facturacion_electronica\\Facturacion_electronica\\dtesv\\company_logos'),
        ),
    ]
