# Generated by Django 4.1.13 on 2024-05-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='municipio',
            field=models.ForeignKey(blank=True, db_column='municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emisor_municipio', to='dtesv.c013municipio'),
        ),
    ]
