# Generated by Django 4.1.13 on 2024-03-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0002_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='sucursal_id',
            field=models.ForeignKey(db_column='sucursal_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_sucursales', to='dtesv.sucursales'),
        ),
    ]
