# Generated by Django 4.1.13 on 2024-05-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0002_alter_emisor_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.IntegerField()),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.CharField(max_length=255)),
            ],
        ),
    ]
