# Generated by Django 4.1.13 on 2024-03-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0003_documentos_sucursal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursal_company', to='dtesv.company'),
        ),
    ]
