# Generated by Django 4.1.9 on 2023-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0003_documentos_email_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='totalIVAretenido',
            field=models.DecimalField(blank=True, db_column='totalIVAretenido', decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='totalSujetoRetenido',
            field=models.DecimalField(blank=True, db_column='totalSujetoRetenido', decimal_places=6, max_digits=18, null=True),
        ),
    ]
