# Generated by Django 4.1.9 on 2023-10-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0004_documentos_totalivaretenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosdetalle',
            name='codigoRetencionMH',
            field=models.ForeignKey(blank=True, db_column='codigoRetencionMH', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_codigoRetencionMH', to='dtesv.c006retencioniva'),
        ),
        migrations.AddField(
            model_name='documentosdetalle',
            name='fechaEmision',
            field=models.DateField(blank=True, db_column='fechaEmision', null=True),
        ),
        migrations.AddField(
            model_name='documentosdetalle',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, db_column='tipoDoc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_tipoDoc', to='dtesv.c007tipogeneraciondoc'),
        ),
        migrations.AddField(
            model_name='documentosdetalle',
            name='tipoDte',
            field=models.ForeignKey(blank=True, db_column='tipoDte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_detalle_tipoDte', to='dtesv.c002tipodocumento'),
        ),
    ]
