# Generated by Django 4.1.13 on 2023-12-05 20:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0005_documentosdetalle_codigoretencionmh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='selloInvalidacion',
            field=models.CharField(blank=True, db_column='selloInvalidacion', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/opt/DTESV/dtesv/Facturacion_electronica/dtesv/company_logos/'), upload_to=''),
        ),
    ]
