# Generated by Django 4.1.13 on 2024-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0005_alter_documentos_sucursal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursales',
            name='cCredito',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='cDonacion',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='cLiquidacion',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='cRetencion',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='cajaMH',
            field=models.CharField(default='0001', max_length=4),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='docLiquidacion',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='facExportacion',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='factura',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='notaCredito',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='notaDebito',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='notaRemision',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='sujetoExcluido',
            field=models.CharField(default='000000000000001', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='susursalMH',
            field=models.CharField(default='0001', max_length=4),
        ),
    ]
