# Generated by Django 4.1.13 on 2023-12-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0007_contingencias_observacion_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='tipoTransmision',
            field=models.ForeignKey(blank=True, db_column='tipoTransmision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_tipoTransmision', to='dtesv.c004tipotransmision'),
        ),
    ]
