# Generated by Django 4.1.13 on 2023-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0008_documentos_tipotransmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingencias',
            name='selloRecepcion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
