# Generated by Django 4.1.13 on 2024-01-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0009_alter_contingencias_sellorecepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='codigoGenInvalida',
            field=models.CharField(blank=True, db_column='codigoGenInvalida', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='motivoInvalidacion',
            field=models.CharField(blank=True, db_column='motivoInvalidacion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='orden_compra',
            field=models.CharField(blank=True, db_column='orden_compra', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='receptor_origen',
            field=models.ForeignKey(blank=True, db_column='receptor_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_receptor_origen_id', to='dtesv.receptor'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='rutaEntrega',
            field=models.CharField(blank=True, db_column='rutaEntrega', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='receptor',
            name='codigoPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtesv.receptor'),
        ),
    ]
