# Generated by Django 4.1.13 on 2024-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0010_documentos_codigogeninvalida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='orden_compra',
            field=models.CharField(blank=True, db_column='orden_compra', max_length=120, null=True),
        ),
    ]
