# Generated by Django 4.1.13 on 2024-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0011_alter_documentos_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='anuladoErp',
            field=models.BooleanField(db_column='anuladoErp', default=False),
        ),
    ]
