# Generated by Django 4.1.13 on 2024-01-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0013_parametros_url_getconsectivosf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('numdocumento', models.CharField(db_column='numDocumento', max_length=18)),
                ('nrc', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nombrecomercial', models.CharField(db_column='nombreComercial', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('tiporeceptor', models.CharField(blank=True, db_column='tipoReceptor', max_length=10, null=True)),
                ('codactividad', models.ForeignKey(db_column='codActividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_codActividad', to='dtesv.c019actividadeconomica')),
                ('codigoPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtesv.proveedor')),
                ('codpais', models.ForeignKey(blank=True, db_column='codPais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_codpais', to='dtesv.c020pais')),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_departamento', to='dtesv.c012departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_empresa', to='dtesv.emisor')),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_municipio', to='dtesv.c013municipio')),
                ('tipodocumento', models.ForeignKey(blank=True, db_column='tipodocumento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_tipo_documento_identific', to='dtesv.c022tipodocumentoidentificacionreceptor')),
                ('tipopersona', models.ForeignKey(blank=True, db_column='tipoPersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_tipopersona', to='dtesv.c029tipopersona')),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': True,
                'unique_together': {('codigo', 'empresa')},
            },
        ),
    ]
