# Generated by Django 4.1.13 on 2024-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtesv', '0015_documentos_proveedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='url_dte_consulta',
            field=models.CharField(default='https://api.dtes.mh.gob.sv/fesv/recepcion/consultadte/', max_length=255),
        ),
    ]
